paths:
  base_output_dir: "./Output/"
  exp_output_dir: "Exp"
  test_output_dir: "Test"
  baseline_name: "Baseline"
  main_name: "Main"

fixed_params:
  t_fixation: 0.3
  t_stim: 0.2
  t_response: 1.3
  t_break: 5
  n_up: 1
  n_down: 1
  min_val: 0.001
  max_val: 0.1
  step_size:  [5.0, 4.5, 4.0, 3.0, 2.0, 1.0, 0.5, 0.2, 0.1] #[2.5, 2.0, 1.5, 1.0, 0.8]
  step_type: 'log'
  reversals: 20 #1
  nullOdds: 0.1

exp_blocks:
  baseline:
    test_trials:  40
    n_trials: 70
    n_blocks: 1
    start_val: 0.03
  
  main:
    test_trials: 50
    n_trials: 70 #50 # total amount of trials per staircase (29 staircases = n_cond * n_intens + 1), n_trials per block = (nCondition * n_intens*n_trials + 0.2*n)/blocks)
    n_blocks: 1 #12 #7
    flanker_conditions:
      - label: "100"
        FC_factor: 1
      # - label: "150"
      #   FC_factor: 1.5
      # - label: "300"
      #   FC_factor: 2
      - label: "800"
        FC_factor: 8
      - label: "4000"
        FC_factor: 40
      # - label: "800"
      #   FC_factor: 8
      # - label: "1600"
      #   FC_factor: 16
      # - label: "3200"
      #   FC_factor: 32
      # - label: "6400"
      #   FC_factor: 64

stimuli:
  target:
    - object: line
      type: target
      pos: [0, 0]
      angle: 90
      length: 40

  # single_flanker_top:
  #   - object: line
  #     type: flanker
  #     pos: [0, 100]
  #     angle: 90
  #     length: 40
  #   - object: line
  #     type: target
  #     pos: [0, 0]
  #     angle: 90
  #     length: 40
  #   - object: line
  #     type: flanker
  #     pos: [0, -100]
  #     angle: 90
  #     length: 40

  # single_flanker_side_orth:
  #   - object: line
  #     type: flanker
  #     pos: [-50, 0]
  #     angle: 0
  #     length: 40
  #   - object: line
  #     type: target
  #     pos: [0, 0]
  #     angle: 90
  #     length: 40
  #   - object: line
  #     type: flanker
  #     pos: [50, 0]
  #     angle: 0
  #     length: 40

  # triple_flanker:
  #   - object: line
  #     type: flanker
  #     pos: [-50, 100]
  #     angle: 90
  #     length: 40
  #   - object: line
  #     type: flanker
  #     pos: [0, 100]
  #     angle: 90
  #     length: 40
  #   - object: line
  #     type: flanker
  #     pos: [50, 100]
  #     angle: 90
  #     length: 40

  #   - object: line
  #     type: flanker
  #     pos: [-50, 0]
  #     angle: 90
  #     length: 40
  #   - object: line
  #     type: target
  #     pos: [0, 0]
  #     angle: 90
  #     length: 40
  #   - object: line
  #     type: flanker
  #     pos: [50, 0]
  #     angle: 90
  #     length: 40

  #   - object: line
  #     type: flanker
  #     pos: [-50, -100]
  #     angle: 90
  #     length: 40
  #   - object: line
  #     type: flanker
  #     pos: [0, -100]
  #     angle: 90
  #     length: 40
  #   - object: line
  #     type: flanker
  #     pos: [50, -100]
  #     angle: 90
  #     length: 40

  triple_flanker_orth: # sides orthogonal
    - object: line
      type: flanker
      pos: [-50, 100]
      angle: 0
      length: 40
    - object: line
      type: flanker
      pos: [0, 100]
      angle: 90
      length: 40
    - object: line
      type: flanker
      pos: [50, 100]
      angle: 0
      length: 40

    - object: line
      type: flanker
      pos: [-50, 0]
      angle: 0
      length: 40
    - object: line
      type: target
      pos: [0, 0]
      angle: 90
      length: 40
    - object: line
      type: flanker
      pos: [50, 0]
      angle: 0
      length: 40

    - object: line
      type: flanker
      pos: [-50, -100]
      angle: 0
      length: 40
    - object: line
      type: flanker
      pos: [0, -100]
      angle: 90
      length: 40
    - object: line
      type: flanker
      pos: [50, -100]
      angle: 0
      length: 40


#-------------------------------------------------------
  # triple_flanker_orth: # All orthogonal
  #   - object: line
  #     type: flanker
  #     pos: [-50, 100]
  #     angle: 0
  #     length: 40
  #   - object: line
  #     type: flanker
  #     pos: [0, 100]
  #     angle: 0
  #     length: 40
  #   - object: line
  #     type: flanker
  #     pos: [50, 100]
  #     angle: 0
  #     length: 40

  #   - object: line
  #     type: flanker
  #     pos: [-50, 0]
  #     angle: 0
  #     length: 40
  #   - object: line
  #     type: target
  #     pos: [0, 0]
  #     angle: 90
  #     length: 40
  #   - object: line
  #     type: flanker
  #     pos: [50, 0]
  #     angle: 0
  #     length: 40

  #   - object: line
  #     type: flanker
  #     pos: [-50, -100]
  #     angle: 0
  #     length: 40
  #   - object: line
  #     type: flanker
  #     pos: [0, -100]
  #     angle: 0
  #     length: 40
  #   - object: line
  #     type: flanker
  #     pos: [50, -100]
  #     angle: 0
  #     length: 40
  
  # double_flanker:
  #   - object: line
  #     type: flanker
  #     pos: [-50, 100]
  #     angle: 90
  #     length: 40
  #   - object: line
  #     type: flanker
  #     pos: [0, 100]
  #     angle: 90
  #     length: 40
  #   - object: line
  #     type: flanker
  #     pos: [50, 100]
  #     angle: 90
  #     length: 40

  #   - object: line
  #     type: target
  #     pos: [0, 0]
  #     angle: 90
  #     length: 40

  #   - object: line
  #     type: flanker
  #     pos: [-50, -100]
  #     angle: 90
  #     length: 40
  #   - object: line
  #     type: flanker
  #     pos: [0, -100]
  #     angle: 90
  #     length: 50
  #   - object: line
  #     type: flanker
  #     pos: [50, -100]
  #     angle: 90
  #     length: 40



  # triple_flanker_orth: # All triple have orthogonal
  #   - object: line
  #     type: flanker
  #     pos: [-50, 100]
  #     angle: 0
  #     length: 40
  #   - object: line
  #     type: flanker
  #     pos: [0, 100]
  #     angle: 90
  #     length: 40
  #   - object: line
  #     type: flanker
  #     pos: [50, 100]
  #     angle: 0
  #     length: 40

  #   - object: line
  #     type: flanker
  #     pos: [-50, 0]
  #     angle: 0
  #     length: 40
  #   - object: line
  #     type: target
  #     pos: [0, 0]
  #     angle: 90
  #     length: 40
  #   - object: line
  #     type: flanker
  #     pos: [50, 0]
  #     angle: 0
  #     length: 40

  #   - object: line
  #     type: flanker
  #     pos: [-50, -100]
  #     angle: 0
  #     length: 40
  #   - object: line
  #     type: flanker
  #     pos: [0, -100]
  #     angle: 90
  #     length: 40
  #   - object: line
  #     type: flanker
  #     pos: [50, -100]
  #     angle: 0
  #     length: 40