paths:
  base_output_dir: "./Output/"
  exp_output_dir: "Exp"
  test_output_dir: "Test"
  baseline_name: "Baseline"
  main_name: "Main"

fixed_params:
  t_fixation: 0.3
  t_stim: 0.15
  t_response: 1.35
  t_break: 5
  n_up: 1
  n_down: 1
  min_val: 0.0
  max_val: 1.0
  step_sizes: [0.2, 0.11777486946929414, 0.09412049672680665, 0.07521696219251955, 0.06011008864405584, 
    0.04803733960364052,
   0.03838932944950302, 0.030679063989438565, 0.024517358879792867, 0.019593195106848448, 0.015658019951383658,
    0.012513201009886982, 0.01, 0.009, 0.008, 0.007,
    0.006, 0.005, 0.0025] #[0.3613222756796251, 0.2887528741799446, 0.23075859961954892, 0.1844121255921814, 0.1473740615582479, 0.11777486946929414, 0.09412049672680665, 0.07521696219251955, 0.06011008864405584, 0.04803733960364052, 0.03838932944950302, 0.030679063989438565, 0.024517358879792867, 0.019593195106848448, 0.015658019951383658, 0.012513201009886982, 0.01]  #np.logspace(-0.15, -2, 20)
  step_type: 'lin'
  reversals: 20 #1
  nullOdds: 0.1

exp_blocks:
  baseline:
    test_trials:  70
    n_trials: 70
    n_blocks: 1
    start_val: 0.4
  
  main:
    test_trials: 70
    n_trials: 70 #50 # total amount of trials per staircase (29 staircases = n_cond * n_intens + 1), n_trials per block = (nCondition * n_intens*n_trials + 0.2*n)/blocks)
    n_blocks: 12 #7
    flanker_conditions:
      - label: "100"
        FC_factor: 1
      - label: "150"
        FC_factor: 1.5
      - label: "300"
        FC_factor: 3
      - label: "900"
        FC_factor: 9
      - label: "4000"
        FC_factor: 40



      # - label: "800"
      #   FC_factor: 8
      # - label: "1600"
      #   FC_factor: 16
      # - label: "3200"
      #   FC_factor: 32
      # - label: "6400"
      #   FC_factor: 64

# Kapadia uses 30' = 0.5° corresponds to ≈ 0.314 cm by width of 3' = 0.05 deg = 0.0314 cm, 1.65 px -> 2 px
# to get 0.5 deg we need around 16.5 pixels -> 18 px for symmetry

stimuli:
  target:
    - object: line
      type: target
      pos: [0, 0]
      angle: 90
      length: 18

  single_flanker_top:
    - object: line
      type: flanker
      pos: [0, 27]
      angle: 90
      length: 18
    - object: line
      type: target
      pos: [0, 0]
      angle: 90
      length: 18
    - object: line
      type: flanker
      pos: [0, -27]
      angle: 90
      length: 18

  single_flanker_side_orth:
    - object: line
      type: flanker
      pos: [-27, 0]
      angle: 0
      length: 18
    - object: line
      type: target
      pos: [0, 0]
      angle: 90
      length: 18
    - object: line
      type: flanker
      pos: [27, 0]
      angle: 0
      length: 18

  triple_flanker:
    - object: line
      type: flanker
      pos: [-27, 27]
      angle: 90
      length: 18
    - object: line
      type: flanker
      pos: [0, 27]
      angle: 90
      length: 18
    - object: line
      type: flanker
      pos: [27, 27]
      angle: 90
      length: 18

    - object: line
      type: flanker
      pos: [-27, 0]
      angle: 90
      length: 18
    - object: line
      type: target
      pos: [0, 0]
      angle: 90
      length: 18
    - object: line
      type: flanker
      pos: [27, 0]
      angle: 90
      length: 18

    - object: line
      type: flanker
      pos: [-27, -27]
      angle: 90
      length: 18
    - object: line
      type: flanker
      pos: [0, -27]
      angle: 90
      length: 18
    - object: line
      type: flanker
      pos: [27, -27]
      angle: 90
      length: 18

  triple_flanker_orth: # sides orthogonal
    - object: line
      type: flanker
      pos: [-27, 27]
      angle: 0
      length: 18
    - object: line
      type: flanker
      pos: [0, 27]
      angle: 90
      length: 18
    - object: line
      type: flanker
      pos: [27, 27]
      angle: 0
      length: 18

    - object: line
      type: flanker
      pos: [-27, 0]
      angle: 0
      length: 18
    - object: line
      type: target
      pos: [0, 0]
      angle: 90
      length: 18
    - object: line
      type: flanker
      pos: [27, 0]
      angle: 0
      length: 18

    - object: line
      type: flanker
      pos: [-27, -27]
      angle: 0
      length: 18
    - object: line
      type: flanker
      pos: [0, -27]
      angle: 90
      length: 18
    - object: line
      type: flanker
      pos: [27, -27]
      angle: 0
      length: 18


#-------------------------------------------------------
  # triple_flanker_orth: # All orthogonal
  #   - object: line
  #     type: flanker
  #     pos: [-50, 100]
  #     angle: 0
  #     length: 40
  #   - object: line
  #     type: flanker
  #     pos: [0, 100]
  #     angle: 0
  #     length: 40
  #   - object: line
  #     type: flanker
  #     pos: [50, 100]
  #     angle: 0
  #     length: 40

  #   - object: line
  #     type: flanker
  #     pos: [-50, 0]
  #     angle: 0
  #     length: 40
  #   - object: line
  #     type: target
  #     pos: [0, 0]
  #     angle: 90
  #     length: 40
  #   - object: line
  #     type: flanker
  #     pos: [50, 0]
  #     angle: 0
  #     length: 40

  #   - object: line
  #     type: flanker
  #     pos: [-50, -100]
  #     angle: 0
  #     length: 40
  #   - object: line
  #     type: flanker
  #     pos: [0, -100]
  #     angle: 0
  #     length: 40
  #   - object: line
  #     type: flanker
  #     pos: [50, -100]
  #     angle: 0
  #     length: 40
  
  # double_flanker:
  #   - object: line
  #     type: flanker
  #     pos: [-50, 100]
  #     angle: 90
  #     length: 40
  #   - object: line
  #     type: flanker
  #     pos: [0, 100]
  #     angle: 90
  #     length: 40
  #   - object: line
  #     type: flanker
  #     pos: [50, 100]
  #     angle: 90
  #     length: 40

  #   - object: line
  #     type: target
  #     pos: [0, 0]
  #     angle: 90
  #     length: 40

  #   - object: line
  #     type: flanker
  #     pos: [-50, -100]
  #     angle: 90
  #     length: 40
  #   - object: line
  #     type: flanker
  #     pos: [0, -100]
  #     angle: 90
  #     length: 50
  #   - object: line
  #     type: flanker
  #     pos: [50, -100]
  #     angle: 90
  #     length: 40



  # triple_flanker_orth: # All triple have orthogonal
  #   - object: line
  #     type: flanker
  #     pos: [-50, 100]
  #     angle: 0
  #     length: 40
  #   - object: line
  #     type: flanker
  #     pos: [0, 100]
  #     angle: 90
  #     length: 40
  #   - object: line
  #     type: flanker
  #     pos: [50, 100]
  #     angle: 0
  #     length: 40

  #   - object: line
  #     type: flanker
  #     pos: [-50, 0]
  #     angle: 0
  #     length: 40
  #   - object: line
  #     type: target
  #     pos: [0, 0]
  #     angle: 90
  #     length: 40
  #   - object: line
  #     type: flanker
  #     pos: [50, 0]
  #     angle: 0
  #     length: 40

  #   - object: line
  #     type: flanker
  #     pos: [-50, -100]
  #     angle: 0
  #     length: 40
  #   - object: line
  #     type: flanker
  #     pos: [0, -100]
  #     angle: 90
  #     length: 40
  #   - object: line
  #     type: flanker
  #     pos: [50, -100]
  #     angle: 0
  #     length: 40